@@@ M&M Sortingmachine
@@@ -------------------------------------------------------------------
@@@ group members:
@@@		- Demiroez Dilara
@@@		- Gonther, Levin
@@@		- Grajczak, Benjamin
@@@		- Pfister, Marc
@@@ target:	 Raspberry Pi Zero
@@@	date:	 2020/01/27
@@@	verison: 1.0.0
@@@ -------------------------------------------------------------------
@@@ This document deals with the following tasks:
@@@		- Method to get access to the gpio memory
@@@ 	- Method to get access to the memory for timers and interrupts
@@@ -------------------------------------------------------------------
